@startuml
' convert it with additional command line argument -DRELATIVE_INCLUDE="." to use locally
!if %variable_exists("RELATIVE_INCLUDE")
  !include ./../C4_App.puml
!else
  !include https://raw.githubusercontent.com/laibe/C4-PlantUML/master/C4_App.puml
!endif

Person(a, "Person A")
App(b, "App B", "techn")
System(c, "System C")
App(d, "App D", "techn")
App_Ext(e, "Ext. App E", "techn")

Rel_R(a, b, "calls")
Rel_D(b, c, "uses")
Rel_D(c, d, "uses")
Rel_R(d, e, "updates")

SHOW_FLOATING_LEGEND()
Lay_Distance(LEGEND(), e, 1)
@enduml
